### ISSUE TITLE
App fails to open on Windows 10/11

### ISSUE THREAD

**Issue by AlexAsitimbay** [relagit/relagit#23]
### What happened?

Al momento de descargarme el zip en windows, al ejecutar el .exe no se esta ejecutando el programa, solamente sale como una tarea en segundo plano pero nunca se abre

*At the time of downloading the zip on windows, when I run the.exe the program is not running, it only comes out as a background task but it never opens*

### Version

0.14.12

### What systems are you seeing the problem on?

Windows

### Confirmations

- [X] I have searched open and closed issues for duplicates
- [X] I have read the relevant documentation
- [X] I have read the CONTRIBUTING document
- [X] I have read the CODE_OF_CONDUCT document

**Comment by agatemosu** [comment]
```sh
[RelaGit] Startup (production)
[RelaGit] Version: 0.14.12
[RelaGit] Running on: win32 x64
[1260:0507/171317.620:ERROR:cache_util_win.cc(20)] Unable to move the cache: Acceso denegado. (0x5)
[1260:0507/171317.620:ERROR:cache_util_win.cc(20)] Unable to move the cache: Acceso denegado. (0x5)
[1260:0507/171317.620:ERROR:disk_cache.cc(208)] Unable to create cache
[1260:0507/171317.620:ERROR:gpu_disk_cache.cc(708)] Gpu Cache Creation failed: -2
[1260:0507/171317.620:ERROR:disk_cache.cc(208)] Unable to create cache
[1260:0507/171317.620:ERROR:gpu_disk_cache.cc(708)] Gpu Cache Creation failed: -2
[11660:0507/171318.346:ERROR:cache_util_win.cc(20)] Unable to move the cache: Acceso denegado. (0x5)
[11660:0507/171318.346:ERROR:disk_cache.cc(208)] Unable to create cache
```

**Comment by AlexAsitimbay** [comment]
> ```shell
> [RelaGit] Startup (production)
> [RelaGit] Version: 0.14.12
> [RelaGit] Running on: win32 x64
> [1260:0507/171317.620:ERROR:cache_util_win.cc(20)] Unable to move the cache: Access denied. (0x5)
> [1260:0507/171317.620:ERROR:cache_util_win.cc(20)] Unable to move the cache: Access denied. (0x5)
> [1260:0507/171317.620:ERROR:disk_cache.cc(208)] Unable to create cache
> [1260:0507/171317.620:ERROR:gpu_disk_cache.cc(708)] Gpu Cache Creation failed: -2
> [1260:0507/171317.620:ERROR:disk_cache.cc(208)] Unable to create cache
> [1260:0507/171317.620:ERROR:gpu_disk_cache.cc(708)] Gpu Cache Creation failed: -2
> [11660:0507/171318.346:ERROR:cache_util_win.cc(20)] Unable to move the cache: Access denied. (0x5)
> [11660:0507/171318.346:ERROR:disk_cache.cc(208)] Unable to create cache
> ```

Hello, how are you, sorry, and in this case what should I do to correct the problem?

**Comment by TheCommieAxolotl** [comment]
Hey there! Thanks for creating the issue, This is something managed by Chromium and out of my control, A solution I've seen in the vscode repo is to **delete**
```
C:\Users\xxx\AppData\Roaming\relagit\Cache\Cache_Data
```

or, @AlexAsitimbay since it seems to say "Access denied.", have you tried running as administrator?

---

¡Hola! Gracias por crear el problema. Esto es algo administrado por Chromium y fuera de mi control. Una solución que he visto en el repositorio de vscode es **eliminar**

```
C:\Users\xxx\AppData\Roaming\relagit\Cache\Cache_Data
```

**Comment by agatemosu** [comment]
Nope, neither deleting the folder nor opening it with administrator works

**Comment by AlmendrosCarmona** [comment]
I does not work for me neither..

**Comment by alexmncn78** [comment]
This also happens to me, Im using Windows 11.

**Comment by FedericoRuiz98** [comment]
Same issue here with Windows 10

**Comment by benjaminpeuple** [comment]
Same issue with Windows 10.
Work with Linux Ubuntu 24.04 LTS.

**Comment by caioraphael1** [comment]
Same for me, using win10

**Comment by TheCommieAxolotl** [comment]
If this does not fix the issue, please mention me and i'll re-open

**Comment by caioraphael1** [comment]
@TheCommieAxolotl I've tested this new version, but the app still doesn't open. It shows on the task manager, but doesn't open. I've closed it in the task manager and opened it as Adm, but without luck.

**Comment by TheCommieAxolotl** [comment]
Is there anything different in the logs if you open it from the command line?

**Comment by agatemosu** [comment]
I got this:

```
INFO: Could not find files for the given pattern(s).
```

**Comment by markox92** [comment]
Same here I can see it in task manager as process but windows does not show.
**Windows 11**

```
❯ [RelaGit] Startup (production)
[RelaGit] Version: 0.16.1
[RelaGit] Running on: win32 x64
[RelaGit] Commit: 758349d
INFO: Could not find files for the given pattern(s).
INFO: Could not find files for the given pattern(s).
INFO: Could not find files for the given pattern(s).
INFO: Could not find files for the given pattern(s).
INFO: Could not find files for the given pattern(s).
INFO: Could not find files for the given pattern(s).
```

**Comment by TheCommieAxolotl** [comment]
can you send the output (redacted if needed) of `where git`?

**Comment by markox92** [comment]
> can you send the output (redacted if needed) of `where git`?

What you mean ?



BTW also I can build from source, any idea what is problem ?


```
…\relagit via  main
❯ pnpm i
Lockfile is up to date, resolution step is skipped
Packages: +969
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Downloading typescript@5.4.5: 5.83 MB/5.83 MB, done
Downloading 7zip-bin@5.2.0: 5.63 MB/5.63 MB, done
Downloading app-builder-bin@4.0.0: 45.10 MB/45.10 MB, done
Progress: resolved 0, reused 0, downloaded 923, added 969, done
node_modules/esbuild: Running postinstall script, done in 580ms
node_modules/electron: Running postinstall script, done in 21.5s
node_modules/electron-vite/node_modules/esbuild: Running postinstall script, done in 573ms
node_modules/vite/node_modules/esbuild: Running postinstall script, done in 1.1s

> relagit@0.16.2 postinstall C:\Users\amn\Desktop\relagit
> node ./build/icons.mjs

Icons copied successfully!
Done in 49s
…\relagit via  main 52s
❯ pnpm build

> relagit@0.16.2 build C:\Users\amn\Desktop\relagit
> electron-vite build

vite v5.3.1 building SSR bundle for production...
✓ 0 modules transformed.
x Build failed in 54ms
error during build:
[transform-file] [vite-plugin-replace]: The replacement option 'to' is not of type 'string' or 'Function'
file: C:/Users/amn/Desktop/relagit/packages/main/src/index.ts
    at C:\Users\amn\Desktop\relagit\node_modules\vite-plugin-replace\index.js:21:23
    at Array.forEach (<anonymous>)
    at execSrcReplacements (C:\Users\amn\Desktop\relagit\node_modules\vite-plugin-replace\index.js:14:22)
    at Object.transform (C:\Users\amn\Desktop\relagit\node_modules\vite-plugin-replace\index.js:45:27)
    at Object.handler (file:///C:/Users/amn/Desktop/relagit/node_modules/vite/dist/node/chunks/dep-BcXSligG.js:65907:15)
    at file:///C:/Users/amn/Desktop/relagit/node_modules/vite/node_modules/rollup/dist/es/shared/node-entry.js:19774:40
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
 ELIFECYCLE  Command failed with exit code 1.
```

**Comment by TheCommieAxolotl** [comment]
that means you don't have a populated `.env` file, (you can rename `.env.example` to `.env`)

**Comment by TheCommieAxolotl** [comment]
> What exactly did you mean?

Just run ```ps
where git
``` 

in a terminal/shell

**Comment by agatemosu** [comment]
No output

**Comment by markox92** [comment]
> > What exactly did you mean?
> 
> Just run
> 
> ```postscript
> where git
> ```
> 
> in a terminal/shell

![image](https://github.com/relagit/relagit/assets/159203552/cc241835-ad63-48eb-b559-86577002fc0d)

**Comment by markox92** [comment]
> populated `.env`

Do i need to populate all fields or just GITHUB_CLIENT_ID? Or I can leave it as in example ?

**Comment by benjaminpeuple** [comment]
With the new version (like the old one) it doesn't work although the process really exists when I try to open the application.

When I try to build the project myself, via the pnpm commands in readme.md :

`pnpm i`

![Tabby_9DcYyQXfHb](https://github.com/relagit/relagit/assets/168526983/7efb45f9-bcbf-482a-8b18-791b2b17a619)

`pnpm build`
![Tabby_CLekiPl3mk](https://github.com/relagit/relagit/assets/168526983/1f840271-349f-485f-9c24-88aba293f782)

I added the `.env` file by copying `.env.example`

**Comment by agatemosu** [comment]
> I also tried to download the first release, it opens correctly on Windows.

the version that broke is 0.14.1

**Comment by benjaminpeuple** [comment]
I just fixed the build problem but even when creating a build the application does not open.
In the `electron.vite.config.ts` configuration file I added ternary operators to avoid the error :

```bash
[transform-file] [vite-plugin-replace]: The replacement option 'to' is not of type 'string' or 'Function'
```

Like this :

```ts
const commonPlugins: import('vite').PluginOption = [
	tsconfig(),
	replaceCodePlugin({
		replacements: [
			{
				from: /__NODE_ENV__/g,
				to: JSON.stringify(IS_DEV ? 'development' : 'production')
			},
			{
				from: /__COMMIT_HASH__/g,
				to: JSON.stringify(GIT_COMMIT_HASH)
			},
			{
				from: /__GITHUB_CLIENT_ID__/g,
				to: process.env.GITHUB_CLIENT_ID ? JSON.stringify(process.env.GITHUB_CLIENT_ID) : '""'
			},
			{
				from: /__GITLAB_CLIENT_ID__/g,
				to: process.env.GITLAB_CLIENT_ID ? JSON.stringify(process.env.GITLAB_CLIENT_ID) : '""'
			},
			{
				from: /__CODEBERG_CLIENT_ID__/g,
				to: process.env.CODEBERG_CLIENT_ID ? JSON.stringify(process.env.CODEBERG_CLIENT_ID) : '""'
			},
			{
				from: /__AI_API_URL__/g,
				to: process.env.AI_API_URL ? JSON.stringify(process.env.AI_API_URL) : '""'
			},
			{
				from: /__AI_API_PASSWORD__/g,
				to: process.env.AI_API_PASSWORD ? JSON.stringify(process.env.AI_API_PASSWORD) : '"'
			}
		]
	})
];
```

By doing this, I no longer have any errors during the build. However, the application does not launch despite a clean build on Windows directly, the processes do indeed exist as for the last release.

**Comment by benjaminpeuple** [comment]
I investigated a little more about the strange behavior of electron builder.

When I build for Windows, `appOutDir` generates `out\win-unpacked`.

When I open the application through this folder, I have to end the process that starts and relaunch the application for it to actually open.

If anyone has any idea for this problem?

**Comment by TheCommieAxolotl** [comment]
> > I also tried to download the first release, it opens correctly on Windows.
> 
> the version that broke is 0.14.1 (in 0.14.0 opens)

The only thing I can see that would have broken the app is upgrading to electron 29, I'll look around a bit more.

**Comment by pietryszak** [comment]
Same issue version 0.16.7

**Comment by WarFiN123** [comment]
Duplicated #38 @TheCommieAxolotl u can close this issue

**Comment by Lovasz-Akos** [comment]
same here,

```log
[RelaGit] Startup (production)
[RelaGit] Version: 0.16.7
[RelaGit] Running on: win32 x64
[RelaGit] Commit: 2efcc5c
INFO: Could not find files for the given pattern(s).
INFO: Could not find files for the given pattern(s).
INFO: Could not find files for the given pattern(s).
INFO: Could not find files for the given pattern(s).
INFO: Could not find files for the given pattern(s).
INFO: Could not find files for the given pattern(s).
```

**Comment by Lovasz-Akos** [comment]
> No output with PowerShell (is an alias of `Where-Object`, `where.exe git` works). With CMD I get `C:\Program Files\Git\cmd\git.exe`

also same as this, no output in PowerShell but get a correct path from CMD

**Comment by WarFiN123** [comment]
> > No output with PowerShell (is an alias of `Where-Object`, `where.exe git` works). With CMD I get `C:\Program Files\Git\cmd\git.exe`
> 
> also same as this, no output in PowerShell but get a correct path from CMD

well for me,
![image](https://github.com/user-attachments/assets/50914155-b615-4895-aa25-d56ab3440e23)
only 'where.exe' returns an output whereas 'where' doesn't

**Comment by rwolf2467** [comment]
I have installed RelaGit via the installer on the website, but it doesn't work there either.

**Comment by goran-w** [comment]
```
C:\Program Files\RelaGit>
[RelaGit] Startup (production)
[RelaGit] Version: 0.16.8
[RelaGit] Running on: win32 x64
[RelaGit] Commit: 35dc216
INFO: Could not find files for the given pattern(s).
INFO: Could not find files for the given pattern(s).
INFO: Could not find files for the given pattern(s).
INFO: Could not find files for the given pattern(s).
INFO: Could not find files for the given pattern(s).
INFO: Could not find files for the given pattern(s).

C:\Program Files\RelaGit>where git
C:\Program Files\Git\cmd\git.exe
```

**Comment by Stream5710** [comment]
Same here on Windows 10 22H2 running RelaGit installed via the installer from the website.

```
[19332:1023/095645.838:ERROR:cache_util_win.cc(20)] Unable to move the cache: アクセスが拒否されました。 (0x5)
[19332:1023/095645.839:ERROR:disk_cache.cc(208)] Unable to create cache
[RelaGit] Startup (production)
[RelaGit] Version: 0.16.8
[RelaGit] Running on: win32 x64
[RelaGit] Commit: 35dc216
```
The Japanese text says "access denied"

**Comment by alrcatraz** [comment]
happen the same on my machine
Software: Downloaded 2025-01-19 UTC+0 14:30 version 0.16.8
OS: Windows 11 Pro Build 27774

**Comment by TheDevelolper** [comment]
Installed on Windows 11 today and yeah it's not working. Uninstalling and forgetting about it now.

**Comment by SvenKribitz** [comment]
Yeah, it is active in the task manager with minimal usage but the GUI doesn't start at all.
![Image](https://github.com/user-attachments/assets/b5b1e9e4-5263-4c5e-9f63-053e4c29efc3)
Winver 26100.3037
